spring:
  datasource:
    url: jdbc:mysql://localhost:3306/poolmanagement?useSSL=false&serverTimezone=UTC
    username: root
    password: 1
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 10
  main:
    allow-circular-references: true
  messages:
    encoding: UTF-8
pool-tour:
  security:
    authentication:
      jwt:
        base64-secret: MmMyY2IzNTYtZmQ0YS00MzZmLTljMDUtNzMxMjkwNjY5MjdkoiseSAndeAAWCCnKQEnesx
        token-validity-in-seconds: 86400
        refresh-token-validity-in-seconds: 604800
        token-validity-in-seconds-for-remember-me: 2592000
    allow-origins: http://localhost:3000,http://localhost:3001,http://localhost:*,https://localhost:3000

authentication:
  password:
    default: 1q2w3e*
encoder:
  password:
    salt: HXwHPI8v2YsLojbYHuILJC
    iterations: 600000
    length: 256
    algorithm: PBKDF2WithHmacSHA256